# Generated by Django 5.2.12 on 2026-03-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0002_documentotecnico_materia_prima'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentotecnico',
            options={'ordering': ['-creado_en', 'titulo'], 'verbose_name': 'Documento técnico', 'verbose_name_plural': 'Documentación técnica'},
        ),
        migrations.AlterField(
            model_name='documentotecnico',
            name='tipo_documento',
            field=models.CharField(choices=[('FICHA_TECNICA', 'Ficha técnica'), ('PROCEDIMIENTO', 'Procedimiento normalizado / procedimiento operativo estándar')], max_length=30),
        ),
    ]
