# Generated by Django 5.2.12 on 2026-03-17 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulaciones', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formulacion',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulaciondetalle',
            name='formulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='formulaciones.formulacion'),
        ),
        migrations.AddField(
            model_name='formulaciondetalle',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_formulacion', to='inventario.materiaprima'),
        ),
        migrations.AddField(
            model_name='formulacion',
            name='materias_primas',
            field=models.ManyToManyField(related_name='formulaciones', through='formulaciones.FormulacionDetalle', to='inventario.materiaprima'),
        ),
        migrations.AlterUniqueTogether(
            name='formulaciondetalle',
            unique_together={('formulacion', 'materia_prima')},
        ),
    ]
