# Generated by Django 5.2.12 on 2026-03-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('PROXIMA_CADUCIDAD', 'Proxima caducidad'), ('CADUCADA', 'Caducada'), ('STOCK_BAJO', 'Stock bajo'), ('SIN_STOCK', 'Sin stock')], max_length=30)),
                ('mensaje', models.TextField()),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Critica')], max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('REVISADA', 'Revisada'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
