FORMULACIONES_BASE = [
    {
        "codigo": "FN/2003/EX/001",
        "nombre": "Agua conservante",
        "categoria": "EXCIPIENTE",
        "tipo_formulacion": "Solucion",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Solucion base conservante para preparaciones magistrales.",
        "detalles": [
            {"nombre": "Solución concentrada de hidroxibenzoatos", "cantidad": "1", "unidad_medida": "%", "orden": 1},
            {"nombre": "Agua purificada", "cantidad": "99", "unidad_medida": "%", "orden": 2},
        ],
    },
    {
        "codigo": "FN/2003/EX/002",
        "nombre": "Crema base de Beeler",
        "categoria": "EXCIPIENTE",
        "tipo_formulacion": "Crema",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Base cremosa de uso frecuente en formulacion magistral.",
        "detalles": [
            {"nombre": "Alcohol cetilico", "cantidad": "15", "unidad_medida": "%", "orden": 1},
            {"nombre": "Cera blanca de abeja", "cantidad": "12", "unidad_medida": "%", "orden": 2},
            {"nombre": "Propilenglicol", "cantidad": "10", "unidad_medida": "%", "orden": 3},
            {"nombre": "Laurilsulfato de sodio", "cantidad": "2", "unidad_medida": "%", "orden": 4},
            {"nombre": "Agua conservante", "cantidad": "72", "unidad_medida": "%", "orden": 5},
        ],
    },
    {
        "codigo": "FN/2003/FMT/008",
        "nombre": "Gel anestesico de lidocaina",
        "categoria": "MAGISTRAL_TIPIFICADA",
        "tipo_formulacion": "Gel",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Formula magistral tipificada en gel.",
        "detalles": [
            {"nombre": "Lidocaina, hidrocloruro de", "cantidad": "1", "unidad_medida": "%", "orden": 1},
            {"nombre": "Carmelosa sodica", "cantidad": "2", "unidad_medida": "%", "orden": 2},
            {"nombre": "Glicerol", "cantidad": "10", "unidad_medida": "%", "orden": 3},
            {"nombre": "Agua purificada", "cantidad": "87", "unidad_medida": "%", "orden": 4},
        ],
    },
    {
        "codigo": "FN/2003/PO/029",
        "nombre": "Urea crema al 15%",
        "categoria": "PREPARADO_OFICIAL",
        "tipo_formulacion": "Crema",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Preparado oficial a base de urea.",
        "detalles": [
            {"nombre": "Urea USP", "cantidad": "15", "unidad_medida": "%", "orden": 1},
            {"nombre": "Emulsion O/A no ionica 1", "cantidad": "85", "unidad_medida": "%", "orden": 2},
        ],
    },
    {
        "codigo": "FN/2003/EX/005",
        "nombre": "Emulsion A/O",
        "categoria": "EXCIPIENTE",
        "tipo_formulacion": "Emulsion",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Excipiente base de emulsion agua en aceite.",
        "detalles": [
            {"nombre": "Parafina liquida", "cantidad": "56", "unidad_medida": "%", "orden": 1},
            {"nombre": "Palmitato de cetilo", "cantidad": "12.5", "unidad_medida": "%", "orden": 2},
            {"nombre": "Cera blanca de abeja", "cantidad": "12", "unidad_medida": "%", "orden": 3},
            {"nombre": "Borax", "cantidad": "0.5", "unidad_medida": "%", "orden": 4},
            {"nombre": "Agua purificada", "cantidad": "19", "unidad_medida": "%", "orden": 5},
        ],
    },
    {
        "codigo": "FN/2003/EX/010",
        "nombre": "Emulsion O/A no ionica 1",
        "categoria": "EXCIPIENTE",
        "tipo_formulacion": "Emulsion",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Excipiente base de emulsion aceite en agua no ionica.",
        "detalles": [
            {"nombre": "O/A no ionica", "cantidad": "22", "unidad_medida": "%", "orden": 1},
            {"nombre": "Aceite de almendras dulces virgen", "cantidad": "3", "unidad_medida": "%", "orden": 2},
            {"nombre": "Butilhidroxitolueno", "cantidad": "0.20", "unidad_medida": "%", "orden": 3},
            {"nombre": "Propilenglicol", "cantidad": "5", "unidad_medida": "%", "orden": 4},
            {"nombre": "Agua conservante", "cantidad": "69.8", "unidad_medida": "%", "orden": 5},
        ],
    },
    {
        "codigo": "FN/2003/EX/017",
        "nombre": "Gel de metilcelulosa",
        "categoria": "EXCIPIENTE",
        "tipo_formulacion": "Gel",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Excipiente gelificado a base de metilcelulosa.",
        "detalles": [
            {"nombre": "Metilcelulosa", "cantidad": "4", "unidad_medida": "%", "orden": 1},
            {"nombre": "Propilenglicol", "cantidad": "5", "unidad_medida": "%", "orden": 2},
            {"nombre": "Cetrimida", "cantidad": "0.5", "unidad_medida": "%", "orden": 3},
            {"nombre": "Agua purificada", "cantidad": "90.5", "unidad_medida": "%", "orden": 4},
        ],
    },
    {
        "codigo": "FN/2003/EX/019",
        "nombre": "Gel hidroalcoholico de metilcelulosa",
        "categoria": "EXCIPIENTE",
        "tipo_formulacion": "Gel hidroalcoholico",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Gel hidroalcoholico base para formulaciones topicas.",
        "detalles": [
            {"nombre": "Metilcelulosa", "cantidad": "4", "unidad_medida": "%", "orden": 1},
            {"nombre": "Propilenglicol", "cantidad": "5", "unidad_medida": "%", "orden": 2},
            {"nombre": "Etanol", "cantidad": "10", "unidad_medida": "%", "orden": 3},
            {"nombre": "Cetrimida", "cantidad": "0.5", "unidad_medida": "%", "orden": 4},
            {"nombre": "Agua purificada", "cantidad": "90.5", "unidad_medida": "%", "orden": 5},
        ],
    },
    {
        "codigo": "FN/2003/EX/021",
        "nombre": "Gel neutro hidroalcoholico",
        "categoria": "EXCIPIENTE",
        "tipo_formulacion": "Gel hidroalcoholico",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Gel neutro hidroalcoholico de uso base.",
        "detalles": [
            {"nombre": "Carbomero 940", "cantidad": "1", "unidad_medida": "%", "orden": 1},
            {"nombre": "Etanol 96%", "cantidad": "10", "unidad_medida": "%", "orden": 2},
            {"nombre": "Propilenglicol", "cantidad": "5", "unidad_medida": "%", "orden": 3},
            {"nombre": "Agua conservante", "cantidad": "84", "unidad_medida": "%", "orden": 4},
        ],
    },
    {
        "codigo": "FN/2003/EX/003",
        "nombre": "Crema consistente hidrofila 1",
        "categoria": "EXCIPIENTE",
        "tipo_formulacion": "Crema",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Excipiente crema consistente hidrofilica.",
        "detalles": [
            {"nombre": "Alcohol estearilico", "cantidad": "25", "unidad_medida": "%", "orden": 1},
            {"nombre": "Parafina filante", "cantidad": "25", "unidad_medida": "%", "orden": 2},
            {"nombre": "Propilenglicol", "cantidad": "12", "unidad_medida": "%", "orden": 3},
            {"nombre": "Laurilsulfato de sodio", "cantidad": "1", "unidad_medida": "%", "orden": 4},
            {"nombre": "Parahidroxibenzoato de metilo", "cantidad": "0.25", "unidad_medida": "%", "orden": 5},
            {"nombre": "Parahidroxibenzoato de propilo", "cantidad": "0.15", "unidad_medida": "%", "orden": 6},
            {"nombre": "Agua purificada", "cantidad": "36.6", "unidad_medida": "%", "orden": 7},
        ],
    },
    {
        "codigo": "FN/2003/EX/016",
        "nombre": "Gel de carmelosa sodica",
        "categoria": "EXCIPIENTE",
        "tipo_formulacion": "Gel",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Excipiente gelificado a base de carmelosa sodica.",
        "detalles": [
            {"nombre": "Carmelosa sodica", "cantidad": "2", "unidad_medida": "%", "orden": 1},
            {"nombre": "Glicerol", "cantidad": "10", "unidad_medida": "%", "orden": 2},
            {"nombre": "Agua conservante", "cantidad": "88", "unidad_medida": "%", "orden": 3},
        ],
    },
    {
        "codigo": "FN/2003/EX/020",
        "nombre": "Gel neutro",
        "categoria": "EXCIPIENTE",
        "tipo_formulacion": "Gel",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Gel neutro base para formulaciones topicas.",
        "detalles": [
            {"nombre": "Carbomero 940", "cantidad": "1", "unidad_medida": "%", "orden": 1},
            {"nombre": "Propilenglicol", "cantidad": "5", "unidad_medida": "%", "orden": 2},
            {"nombre": "Agua conservante", "cantidad": "94", "unidad_medida": "%", "orden": 3},
        ],
    },
    {
        "codigo": "FN/2003/FMT/005",
        "nombre": "Acido salicilico y triamcinolona acetonido, gel de",
        "categoria": "MAGISTRAL_TIPIFICADA",
        "tipo_formulacion": "Gel",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Formula magistral tipificada en gel con acido salicilico y triamcinolona.",
        "detalles": [
            {"nombre": "Acido salicilico", "cantidad": "6", "unidad_medida": "%", "orden": 1},
            {"nombre": "Triamcinolona acetonido", "cantidad": "0.1", "unidad_medida": "%", "orden": 2},
            {"nombre": "Propilenglicol", "cantidad": "60", "unidad_medida": "%", "orden": 3},
            {"nombre": "Hidroxipropil goma guar", "cantidad": "2", "unidad_medida": "%", "orden": 4},
            {"nombre": "Etanol", "cantidad": "6", "unidad_medida": "%", "orden": 5},
            {"nombre": "Agua purificada", "cantidad": "25.9", "unidad_medida": "%", "orden": 6},
        ],
    },
    {
        "codigo": "FN/2003/PO/001",
        "nombre": "Aceite alcanforado",
        "categoria": "PREPARADO_OFICIAL",
        "tipo_formulacion": "Aceite",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Preparado oficial en base oleosa.",
        "detalles": [
            {"nombre": "Mentol racemico", "cantidad": "5", "unidad_medida": "%", "orden": 1},
            {"nombre": "Etanol", "cantidad": "95", "unidad_medida": "%", "orden": 2},
        ],
    },
    {
        "codigo": "FN/2003/PO/012",
        "nombre": "Alcohol mentolado al 5%",
        "categoria": "PREPARADO_OFICIAL",
        "tipo_formulacion": "Solucion",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Preparado oficial alcoholico mentolado.",
        "detalles": [
            {"nombre": "Alcanfor racemico", "cantidad": "10", "unidad_medida": "%", "orden": 1},
            {"nombre": "Aceite de oliva virgen", "cantidad": "90", "unidad_medida": "%", "orden": 2},
        ],
    },
    {
        "codigo": "FN/2003/PO/019",
        "nombre": "Permanganato de potasio, solucion al 1/10.000",
        "categoria": "PREPARADO_OFICIAL",
        "tipo_formulacion": "Solucion",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Preparado oficial en solucion acuosa.",
        "detalles": [
            {"nombre": "Permanganato de potasio", "cantidad": "0.10", "unidad_medida": "%", "orden": 1},
            {"nombre": "Agua purificada", "cantidad": "99.9", "unidad_medida": "%", "orden": 2},
        ],
    },
    {
        "codigo": "PN/2003/PO/018",
        "nombre": "Pasta Lassar",
        "categoria": "PREPARADO_OFICIAL",
        "tipo_formulacion": "Pasta",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Preparado oficial tipo pasta.",
        "detalles": [
            {"nombre": "Oxido de zinc", "cantidad": "25", "unidad_medida": "%", "orden": 1},
            {"nombre": "Almidon de arroz", "cantidad": "25", "unidad_medida": "%", "orden": 2},
            {"nombre": "Vaselina solida", "cantidad": "50", "unidad_medida": "%", "orden": 3},
        ],
    },
    {
        "codigo": "PN/2003/PO/021",
        "nombre": "Pomada alcanforada",
        "categoria": "PREPARADO_OFICIAL",
        "tipo_formulacion": "Pomada",
        "origen": "INSTITUCIONAL",
        "fuente_referencia": "Formulario Nacional 2003",
        "descripcion": "Preparado oficial tipo pomada.",
        "detalles": [
            {"nombre": "Alcanfor racemico", "cantidad": "10", "unidad_medida": "%", "orden": 1},
            {"nombre": "Cera blanca de abeja", "cantidad": "8", "unidad_medida": "%", "orden": 2},
            {"nombre": "Parafina filante", "cantidad": "82", "unidad_medida": "%", "orden": 3},
        ],
    },
]
