# Generated by Django 5.2.12 on 2026-03-20 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("formulaciones", "0005_alter_formulaciondetalle_unidad_medida"),
        ("usuarios", "0004_historialsistema"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoTecnico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("FICHA_TECNICA", "Ficha tecnica"), ("PROCEDIMIENTO", "Procedimiento de elaboracion")],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("archivo", models.FileField(upload_to="documentacion/")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "formulacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_tecnicos",
                        to="formulaciones.formulacion",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos_subidos",
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento tecnico",
                "verbose_name_plural": "Documentacion tecnica",
                "ordering": ["-creado_en", "titulo"],
            },
        ),
    ]
