# Generated by Django 5.2.12 on 2026-03-25 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0001_initial'),
        ('inventario', '0003_materiaprima_requiere_control_caducidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotecnico',
            name='materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_tecnicos', to='inventario.materiaprima'),
        ),
    ]
