# Generated by Django 5.2.12 on 2026-03-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_usuario_debe_cambiar_contrasena"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialSistema",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modulo", models.CharField(max_length=50)),
                ("accion", models.CharField(max_length=100)),
                ("entidad", models.CharField(blank=True, max_length=100)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acciones_historial",
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial del sistema",
                "verbose_name_plural": "Historial del sistema",
                "ordering": ["-fecha"],
            },
        ),
    ]
