# Generated by Django 5.2.12 on 2026-04-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_historialsistema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudrecuperacioncontrasena',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Solicitud de recuperación de contraseña', 'verbose_name_plural': 'Solicitudes de recuperación de contraseña'},
        ),
    ]
