# Generated by Django 5.2.12 on 2026-03-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('numero_cas', models.CharField(blank=True, max_length=50, verbose_name='Numero CAS')),
                ('numero_einecs', models.CharField(blank=True, max_length=50, verbose_name='Numero EINECS')),
                ('lote', models.CharField(max_length=80)),
                ('fecha_elaboracion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('casa_comercial', models.CharField(blank=True, max_length=150)),
                ('stock_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('VENCIDA', 'Vencida')], default='ACTIVA', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Materia prima',
                'verbose_name_plural': 'Materias primas',
                'ordering': ['nombre', 'lote'],
            },
        ),
    ]
