# Generated by Django 5.2.12 on 2026-03-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='requiere_control_caducidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
