# Generated by Django 5.2.12 on 2026-03-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudRecuperacionContrasena",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("correo", models.EmailField(max_length=254)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("PENDIENTE", "Pendiente"), ("ATENDIDA", "Atendida"), ("RECHAZADA", "Rechazada")],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_atencion", models.DateTimeField(blank=True, null=True)),
                (
                    "atendida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_atendidas",
                        to="usuarios.usuario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_recuperacion",
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de recuperacion de contrasena",
                "verbose_name_plural": "Solicitudes de recuperacion de contrasena",
                "ordering": ["-fecha_solicitud"],
            },
        ),
    ]
