# Generated by Django 5.2.12 on 2026-03-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_solicitudrecuperacioncontrasena"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="debe_cambiar_contrasena",
            field=models.BooleanField(default=False),
        ),
    ]
