# Generated by Django 5.2.12 on 2026-03-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_formulacion', models.CharField(max_length=100)),
                ('origen', models.CharField(choices=[('INSTITUCIONAL', 'Institucional'), ('DOCENTE', 'Creada por docente')], max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('EN_REVISION', 'En revision')], default='ACTIVA', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['codigo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='FormulacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Detalle de formulacion',
                'verbose_name_plural': 'Detalles de formulacion',
            },
        ),
    ]
