# Generated by Django 5.2.12 on 2026-03-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulaciondetalle',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Detalle de formulacion', 'verbose_name_plural': 'Detalles de formulacion'},
        ),
        migrations.AddField(
            model_name='formulacion',
            name='categoria',
            field=models.CharField(choices=[('EXCIPIENTE', 'Excipiente'), ('MAGISTRAL_TIPIFICADA', 'Formula magistral tipificada'), ('PREPARADO_OFICIAL', 'Preparado oficial')], default='MAGISTRAL_TIPIFICADA', max_length=30),
        ),
        migrations.AddField(
            model_name='formulacion',
            name='fuente_referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formulaciondetalle',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
