# Generated by Django 5.2.12 on 2026-03-20 10:20

from django.db import migrations, models


def normalizar_categorias(apps, schema_editor):
    Formulacion = apps.get_model("formulaciones", "Formulacion")
    equivalencias = {
        "EXCIPIENTE": "Excipiente",
        "MAGISTRAL_TIPIFICADA": "Formula magistral tipificada",
        "PREPARADO_OFICIAL": "Preparado oficial",
    }
    for formulacion in Formulacion.objects.all():
        categoria_normalizada = equivalencias.get(formulacion.categoria, formulacion.categoria)
        if formulacion.categoria != categoria_normalizada:
            formulacion.categoria = categoria_normalizada
            formulacion.save(update_fields=["categoria"])


class Migration(migrations.Migration):

    dependencies = [
        ("formulaciones", "0003_alter_formulaciondetalle_options_and_more"),
    ]

    operations = [
        migrations.RunPython(normalizar_categorias, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="formulacion",
            name="categoria",
            field=models.CharField(default="Formula magistral tipificada", max_length=100),
        ),
    ]
