# Generated by Django 5.2.12 on 2026-03-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulaciones", "0004_normalizar_categoria_formulacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulaciondetalle",
            name="unidad_medida",
            field=models.CharField(
                choices=[("%", "%"), ("ml", "ml")],
                default="%",
                max_length=10,
            ),
        ),
    ]
