# Generated by Django 5.2.12 on 2026-03-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulaciones", "0005_alter_formulaciondetalle_unidad_medida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulacion",
            name="fuente_referencia",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
